version: "3.8"

services:
  # 통합 에이전트
  integrated_agent:
    build:
      context: ../..
      dockerfile: docker/agents/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AGENT_PORT=8000
      - AGENT_HOST=0.0.0.0
      - LLM_MODEL=gpt-oss:20b
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - MCP_SERVERS=macroeconomic,financial_analysis,stock_analysis,naver_news,tavily_search,kiwoom
    volumes:
      - ../../src:/app/src
      - ../../requirements.txt:/app/requirements.txt
    restart: unless-stopped
    depends_on:
      - macroeconomic_mcp
      - financial_analysis_mcp
      - stock_analysis_mcp
      - naver_news_mcp
      - tavily_search_mcp
      - kiwoom_mcp

  # MCP 서버들
  macroeconomic_mcp:
    build:
      context: ../..
      dockerfile: docker/mcp_servers/Dockerfile
    ports:
      - "8042:8042"
    environment:
      - MCP_SERVER_TYPE=macroeconomic
      - MCP_SERVER_PORT=8042
      - MCP_SERVER_HOST=0.0.0.0
    volumes:
      - ../../src:/app/src
      - ../../requirements.txt:/app/requirements.txt
    command: ["python", "-m", "src.mcp_servers.macroeconomic.server"]
    restart: unless-stopped

  financial_analysis_mcp:
    build:
      context: ../..
      dockerfile: docker/mcp_servers/Dockerfile
    ports:
      - "8041:8041"
    environment:
      - MCP_SERVER_TYPE=financial_analysis
      - MCP_SERVER_PORT=8041
      - MCP_SERVER_HOST=0.0.0.0
    volumes:
      - ../../src:/app/src
      - ../../requirements.txt:/app/requirements.txt
    command: ["python", "-m", "src.mcp_servers.financial_analysis.server"]
    restart: unless-stopped

  stock_analysis_mcp:
    build:
      context: ../..
      dockerfile: docker/mcp_servers/Dockerfile
    ports:
      - "8052:8052"
    environment:
      - MCP_SERVER_TYPE=stock_analysis
      - MCP_SERVER_PORT=8052
      - MCP_SERVER_HOST=0.0.0.0
    volumes:
      - ../../src:/app/src
      - ../../requirements.txt:/app/requirements.txt
    command: ["python", "-m", "src.mcp_servers.stock_analysis.server"]
    restart: unless-stopped

  naver_news_mcp:
    build:
      context: ../..
      dockerfile: docker/mcp_servers/Dockerfile
    ports:
      - "8051:8051"
    environment:
      - MCP_SERVER_TYPE=naver_news
      - MCP_SERVER_PORT=8051
      - MCP_SERVER_HOST=0.0.0.0
    volumes:
      - ../../src:/app/src
      - ../../requirements.txt:/app/requirements.txt
    command: ["python", "-m", "src.mcp_servers.naver_news.server"]
    restart: unless-stopped

  tavily_search_mcp:
    build:
      context: ../..
      dockerfile: docker/mcp_servers/Dockerfile
    ports:
      - "8053:8053"
    environment:
      - MCP_SERVER_TYPE=tavily_search
      - MCP_SERVER_PORT=8053
      - MCP_SERVER_HOST=0.0.0.0
    volumes:
      - ../../src:/app/src
      - ../../requirements.txt:/app/requirements.txt
    command: ["python", "-m", "src.mcp_servers.tavily_search.server"]
    restart: unless-stopped

  kiwoom_mcp:
    build:
      context: ../..
      dockerfile: docker/mcp_servers/Dockerfile
    ports:
      - "8030:8030"
    environment:
      - MCP_SERVER_TYPE=kiwoom
      - MCP_SERVER_PORT=8030
      - MCP_SERVER_HOST=0.0.0.0
    volumes:
      - ../../src:/app/src
      - ../../requirements.txt:/app/requirements.txt
    command: ["python", "-m", "src.mcp_servers.kiwoom.server"]
    restart: unless-stopped

networks:
  default:
    name: agent_network
    driver: bridge
