version: "3.8"

services:
  # 1. 주식 분석 시스템 MCP 서버
  stock_analysis_mcp:
    build:
      context: ../..
      dockerfile: docker/mcp_servers/Dockerfile
    ports:
      - "8052:8052"
    environment:
      - MCP_SERVER_TYPE=stock_analysis
      - MCP_SERVER_PORT=8052
      - MCP_SERVER_HOST=0.0.0.0
    volumes:
      - ../../src:/app/src
      - ../../requirements.txt:/app/requirements.txt
    command: ["python", "-m", "src.mcp_servers.stock_analysis.server"]
    restart: unless-stopped

  # 2. 재무 분석 시스템 MCP 서버
  financial_analysis_mcp:
    build:
      context: ../..
      dockerfile: docker/mcp_servers/Dockerfile
    ports:
      - "8041:8041"
    environment:
      - MCP_SERVER_TYPE=financial_analysis
      - MCP_SERVER_PORT=8041
      - MCP_SERVER_HOST=0.0.0.0
    volumes:
      - ../../src:/app/src
      - ../../requirements.txt:/app/requirements.txt
    command: ["python", "-m", "src.mcp_servers.financial_analysis.server"]
    restart: unless-stopped

  # 3. 데이터 처리 시스템 MCP 서버
  macroeconomic_mcp:
    build:
      context: ../..
      dockerfile: docker/mcp_servers/Dockerfile
    ports:
      - "8042:8042"
    environment:
      - MCP_SERVER_TYPE=macroeconomic
      - MCP_SERVER_PORT=8042
      - MCP_SERVER_HOST=0.0.0.0
    volumes:
      - ../../src:/app/src
      - ../../requirements.txt:/app/requirements.txt
    command: ["python", "-m", "src.mcp_servers.macroeconomic.server"]
    restart: unless-stopped

  # 4. 콘텐츠 수집 시스템 MCP 서버
  naver_news_mcp:
    build:
      context: ../..
      dockerfile: docker/mcp_servers/Dockerfile
    ports:
      - "8051:8051"
    environment:
      - MCP_SERVER_TYPE=naver_news
      - MCP_SERVER_PORT=8051
      - MCP_SERVER_HOST=0.0.0.0
    volumes:
      - ../../src:/app/src
      - ../../requirements.txt:/app/requirements.txt
    command: ["python", "-m", "src.mcp_servers.naver_news.server"]
    restart: unless-stopped

  # 5. 검색 시스템 MCP 서버
  tavily_search_mcp:
    build:
      context: ../..
      dockerfile: docker/mcp_servers/Dockerfile
    ports:
      - "8053:8053"
    environment:
      - MCP_SERVER_TYPE=tavily_search
      - MCP_SERVER_PORT=8053
      - MCP_SERVER_HOST=0.0.0.0
    volumes:
      - ../../src:/app/src
      - ../../requirements.txt:/app/requirements.txt
    command: ["python", "-m", "src.mcp_servers.tavily_search.server"]
    restart: unless-stopped

  # 6. 키움 API 연동 시스템 MCP 서버
  kiwoom_mcp:
    build:
      context: ../..
      dockerfile: docker/mcp_servers/Dockerfile
    ports:
      - "8030:8030"
    environment:
      - MCP_SERVER_TYPE=kiwoom
      - MCP_SERVER_PORT=8030
      - MCP_SERVER_HOST=0.0.0.0
    volumes:
      - ../../src:/app/src
      - ../../requirements.txt:/app/requirements.txt
    command: ["python", "-m", "src.mcp_servers.kiwoom.server"]
    restart: unless-stopped

networks:
  default:
    name: mcp_network
    driver: bridge
